### ISSUE TITLE
Diviner Module not installing

### ISSUE THREAD

**Issue by MrZombie69232** [lro-diviner/divcalib#7]
I tried installing Diviner Module using conda but it says no such module

**Comment by michaelaye** [comment]
There is no conda installation for divcalib, and in general, you most likely do not want this software, as it's mostly only for recalibrating raw data and displaying them. You will be much better of using the higher level data in PDS here: https://pds-geosciences.wustl.edu/lro/lro-l-dlre-4-rdr-v1/lrodlr_1001/ and here: https://pds-geosciences.wustl.edu/lro/lro-l-dlre-4-rdr-v1/lrodlr_1002/

**Comment by michaelaye** [comment]
Also, it would be helpful if your github user name reflects your real name, so that I can relate any emails i have from you potentially.

**Comment by MrZombie69232** [comment]
Hi, 
My name is Satyam Suman 
email:- singh.9616satyam@gmail.com

I am sorry ..I didn't realize that my real name wasn't mentioned . 

I wanted know how level 4 products are generated from RDR files of Diviner and how those raster maps are further generated from those csv files.  Like what softwares being used or it's been generated using python or something .
